### ISSUE TITLE
Support for latest API?

### ISSUE THREAD

**Issue by madisonb** [jkeljo/sisyphus-control#1]
I know this community is small, and even smaller for those who use both Home Assistant and the Sisyphus table, but support for the latest API the table is emitting would be great.

* RGBW Lights (not sure what is exposed here, or if you could customize what is displayed around the ring)
* Playlist errors inside of HA (see below)
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sisyphus/__init__.py", line 123, in close
    await self._table.close()
  File "/usr/local/lib/python3.8/site-packages/sisyphus_control/table.py", line 83, in close
    result = await self._transport.close()
  File "/usr/local/lib/python3.8/site-packages/sisyphus_control/transport.py", line 37, in close
    await self._socket_closed
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/sisyphus_control/transport.py", line 21, in <lambda>
    lambda: self._run_socket())
  File "/usr/local/lib/python3.8/site-packages/sisyphus_control/transport.py", line 67, in _run_socket
    socket.wait(seconds=1)
  File "/usr/local/lib/python3.8/site-packages/socketIO_client_nexus/__init__.py", line 251, in wait
    self._process_packets()
  File "/usr/local/lib/python3.8/site-packages/socketIO_client_nexus/__init__.py", line 278, in _process_packets
    self._process_packet(engineIO_packet)
  File "/usr/local/lib/python3.8/site-packages/socketIO_client_nexus/__init__.py", line 491, in _process_packet
    delegate(parse_socketIO_packet_data(socketIO_packet_data), namespace)
  File "/usr/local/lib/python3.8/site-packages/socketIO_client_nexus/__init__.py", line 513, in _on_event
    namespace._find_packet_callback(event)(*args)
  File "/usr/local/lib/python3.8/site-packages/sisyphus_control/transport.py", line 58, in on_set
    transport._on_set(args)
  File "/usr/local/lib/python3.8/site-packages/sisyphus_control/transport.py", line 75, in _on_set
    asyncio.run_coroutine_threadsafe(
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/sisyphus_control/table.py", line 298, in _try_update_table_state
    if playlist_id not in self._data["playlist_ids"]:
KeyError: 'playlist_ids'
Home Assistant attempting to restart.
Restarting Home Assistant
```
* Proper rendering of the current track inside of Home Assistant
* Etc.

If you have a particular workflow for us to follow, that could help us get on the right track.

**Comment by jkeljo** [comment]
Thanks for the report! To be honest, I've been avoiding upgrading my own table's firmware because I didn't want to deal with the inevitable breakages. Looks like it's time to quit procrastinating. ;) I'll upgrade my table and see about getting this library working against the latest. I don't have an RGBW light ring, so I may need some help on that front.

**Comment by jkeljo** [comment]
I've updated my table to firmware 1.10.73 and I am not seeing this crash. Are you seeing it consistently? Looking at the data stream coming from the table I see a way that the crash could happen, but it requires things to happen *just so*. I'll put a fix in for that issue, but if you're seeing consistent crashes there may be something else going on.

**Comment by jkeljo** [comment]
The API for RGBW has controls for:
- LED primary color (4-byte hex)
- LED secondary color (4-byte hex)
- LED offset (-180 to 180)
- LED white color balance (floating point 0-1 for cold - warm, though the math for this may be done client-side, I can't tell exactly)
- LED pattern ('white', 'solid', 'fade', 'spread', 'comet', 'rainbow', 'paint', 'demo')

I don't actually know what most of this stuff means for the table, but I can try just exposing all of it and letting people play with it and give feedback.

**Comment by jkeljo** [comment]
Ahhh, ran into a case that shows that crash more consistently (though if you're seeing the same thing it looks like your log snippet left out some lines at the start). I'll add a fix for that as well.
